### ISSUE TITLE
Package GTFS states MongoDB, Github States MySQL

### ISSUE THREAD

**Issue by SirPolaris** [BlinkTagInc/node-gtfs#124]
Just a heads up the package at https://www.npmjs.com/package/gtfs/v/0.7.0 states one thing, MongoDB driven, vs here MySQL driven.

I don't know the history of this project, but it might be of importance to you.

**Comment by RoryDungan** [comment]
You're looking at an old version. Looking at the history, it seems that version 2.0.0 switched to SQLite instead of MongoDB. I don't think any version supported MySQL but I could be wrong. 

I just had this problem since I have some code that uses GTFS data in a MongoDB database and was wondering why my pipeline no longer worked after upgrading this package. If you'd like to install the last version that supported MongoDB you can run `npm i -g gtfs@1.10.4`, although I wonder if MongoDB support could ever be added again in future? I found it very useful.

**Comment by SirPolaris** [comment]
Ah thanks, I see my error now. Thanks Google. I thought I was on the freshest, now I see I am not.

While Mongo is life, I think this company (which does transit deployments) found out, as I feel as well, in this kind of static tabled data relational wins. It is just not web friendly, but transit is hardly dynamic.

Rolling your own GTFS isn't too hard, its just the 'relational' connections that get a little messy in mongo (population and type: Schema.Types.ObjectId, ref's)

**Comment by brendannee** [comment]
Thanks for the input.

We may add additional database support in the future for Postgres and mysql.
