### ISSUE TITLE
Cannot use multiple databases at once

### ISSUE THREAD

**Issue by DarkMatterMatt** [BlinkTagInc/node-gtfs#126]
I would like to be able to use DatabaseA while importing DatabaseB (so my app doesn't have any period of downtime where the database is in an invalid state).

## Issue

**At the moment, passing a different sqlitePath results in the library silently ignoring the path and overwriting the old database.**

This is because `openDb()` ignores all config if there is an existing database connection.

[import.js](https://github.com/BlinkTagInc/node-gtfs/blob/master/lib/import.js#L356)
```js
const importGtfs = async (initialConfig) => {
  ...
  const db = await openDb(config)
  ...
}
```

[db.js](https://github.com/BlinkTagInc/node-gtfs/blob/184d69af6c01e3811f3a91867564cd620ed40c35/lib/db.js#L6)
```js
export async function openDb(initialConfig) {
  const config = setDefaultConfig(initialConfig);
  if (!db) {
    db = await open({
      filename: config.sqlitePath,
      driver: sqlite3.Database,
    });
  }

  return db;
}
```

Relevant issue #117.

## Background info

My use case involves importing data from multiple agencies (each of which is updated separately so I need to be able to update one without DROP TABLEing all the others). This could be done by using multiple database files. I think it would be ideal if there was an additional (optional) parameter for library functions to specify the database (see [my branch](https://github.com/DarkMatterMatt/node-gtfs/tree/feat/multiple-databases)). Query functions like `getAgencies()` would have a fourth parameter for the database (defaults to current behaviour, fetching the database using `getDb()`). and `importGtfs()` would look more like:
```js
const importGtfs = async (initialConfig, db) => {
  ...
  db = db ?? await openDb(config)
  ...
}
```

Thanks :)

**Comment by brendannee** [comment]
I hadn't considered multiple dbs, that is a great idea.

I took your branch as inspiration for this PR https://github.com/BlinkTagInc/node-gtfs/pull/127 - I updated it so that it keeps all open dbs available with no concept of "global db", so you can use` getDb({ sqlitePath: 'your path' })` to get at any open db. At the same time, it works for all existing code as if only one db is open, it always returns/uses that.

Check out this branch https://github.com/BlinkTagInc/node-gtfs/pull/127 and see if it achieves what you need and let me know if you have any comments or suggestions on how to improve it.

**Comment by DarkMatterMatt** [comment]
#127 looks great :)
